package scripts;
import java.io.IOException;
import org.openqa.selenium.By;
import atu.testng.reports.ATUReports;
import commonMethods.Config;
import commonMethods.Keywords;
import commonMethods.Utils;
public class AMLPipeline extends Keywords {
	

	/**
	 * Name : Pavan 
	 * Created Date: 01/Aug/2017
	 *  Modified Date:01/Aug/2017
	 * Description:AML PIpeline
	 * 
	 */
	
	public static void amlPipeline() throws IOException {
		String automationName = Utils.getDataFromTestData("amlPipeline", "Automation Name");
		String file1 = Utils.getDataFromTestData("amlPipeline", "OutputFile1");
		String file2 = Utils.getDataFromTestData("amlPipeline", "OutputFile2");
		String file3 = Utils.getDataFromTestData("amlPipeline", "OutputFile3");
		String file4 = Utils.getDataFromTestData("amlPipeline", "OutputFile4");
		String file5 = Utils.getDataFromTestData("amlPipeline", "OutputFile5");
		String file6 = Utils.getDataFromTestData("amlPipeline", "OutputFile6");
		String file7 = Utils.getDataFromTestData("amlPipeline", "OutputFile7");
		waitForElement(dashboard);
		click(dashboard);
		waitForElement(pipeline);
		click(pipeline);
		waitForElement(viewPipeline);
		click(createpipeline);
		defaultWait();
		waitForElement(addPipelineName);
		sendKeys(addPipelineName, automationName);
		waitForElement(addProcess);
		click(addProcess);
		waitForElement(addTransformation);
		click(addTransformation);
		defaultWait();
		waitForElement(chooseTransformation);
		click(chooseTransformation);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file1);
		defaultWait();
		tab();
		click(add);
		defaultWait();
		waitForElement(addProcess);
		click(addProcess);
		waitForElement(addTransformation);
		click(addTransformation);
		defaultWait();
		waitForElement(chooseTransformation);
		click(chooseTransformation);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file2);
		scrollBottom();
		waitForElement(selectFileTransformation);
		click(selectFileTransformation);
		click(add);
		defaultWait();
		waitForElement(addProcess);
		click(addProcess);
		waitForElement(addTransformation);
		click(addTransformation);
		defaultWait();
		waitForElement(chooseTransformation);
		click(chooseTransformation);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file3);
		keyboardArrowDown();
		keyboardArrowDown();
		keyboardArrowDown();
		keyboardArrowDown();
		tab();
		click(add);
		defaultWait();
		waitForElement(addProcess);
		click(addProcess);
		waitForElement(addTransformation);
		click(addTransformation);
		defaultWait();
		waitForElement(chooseTransformation);
		click(chooseTransformation);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file3);
		keyboardArrowDown();
		keyboardArrowDown();
		keyboardArrowDown();
		tab();
		click(add);
		defaultWait();
		waitForElement(addProcess);
		click(addProcess);
		waitForElement(addTransformation);
		click(addTransformation);
		defaultWait();
		waitForElement(chooseTransformation);
		click(chooseTransformation);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file3);
		keyboardArrowDown();
		keyboardArrowDown();
		tab();
		click(add);
		defaultWait();
		waitForElement(addProcess);
		click(addProcess);
		waitForElement(addTransformation);
		click(addTransformation);
		defaultWait();
		waitForElement(chooseTransformation);
		click(chooseTransformation);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file3);
		keyboardArrowDown();
		tab();
		click(add);
		defaultWait();
		waitForElement(addProcess);
		click(addProcess);
		waitForElement(addTransformation);
		click(addTransformation);
		defaultWait();
		waitForElement(chooseTransformation);
		click(chooseTransformation);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file3);
		tab();
		click(add);
		defaultWait();
		click(addProcess);
		waitForElement(addTransformation);
		click(addTransformation);
		defaultWait();
		waitForElement(chooseTransformation);
		click(chooseTransformation);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file4);
		keyboardArrowDown();
		keyboardArrowDown();
		keyboardArrowDown();
		tab();
		click(add);
		defaultWait();
		click(addProcess);
		waitForElement(addTransformation);
		click(addTransformation);
		defaultWait();
		waitForElement(chooseTransformation);
		click(chooseTransformation);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file4);
		keyboardArrowDown();
		keyboardArrowDown();
		tab();
		click(add);
		defaultWait();
		click(addProcess);
		waitForElement(addTransformation);
		click(addTransformation);
		defaultWait();
		waitForElement(chooseTransformation);
		click(chooseTransformation);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file4);
		keyboardArrowDown();
		tab();
		click(add);
		defaultWait();
		click(addProcess);
		waitForElement(addTransformation);
		click(addTransformation);
		defaultWait();
		waitForElement(chooseTransformation);
		click(chooseTransformation);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file4);
		tab();
		click(add);
		defaultWait();
		click(addProcess);
		waitForElement(addTransformation);
		click(addTransformation);
		defaultWait();
		waitForElement(chooseTransformation);
		click(chooseTransformation);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file5);
		keyboardArrowDown();
		keyboardArrowDown();
		tab();
		click(add);
		defaultWait();
		click(addProcess);
		waitForElement(addTransformation);
		click(addTransformation);
		defaultWait();
		waitForElement(chooseTransformation);
		click(chooseTransformation);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file5);
		keyboardArrowDown();
		tab();
		click(add);
		defaultWait();
		click(addProcess);
		waitForElement(addTransformation);
		click(addTransformation);
		defaultWait();
		waitForElement(chooseTransformation);
		click(chooseTransformation);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file5);
		tab();
		click(add);
		defaultWait();
		click(addProcess);
		waitForElement(addTransformation);
		click(addTransformation);
		defaultWait();
		waitForElement(chooseTransformation);
		click(chooseTransformation);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file6);
		tab();
		click(add);
		defaultWait();
		click(addProcess);
		waitForElement(addModel);
		click(addModel);
		defaultWait();
		waitForElement(chooseModel);
		click(chooseModel);
		waitForElement(selectTransformation);
		sendKeys(selectTransformation, file7);
		tab();
		waitForElement(chooseAnalyzer);
		click(chooseAnalyzer);
		tab();
		click(add);
		defaultWait();
		waitForElement(runAutomation);
		click(runAutomation);
		waitForElement(processRunAutomation);
		click(processRunAutomation);
		
	}
}
